### ISSUE TITLE
Indented Sass syntax?

### ISSUE THREAD

**Issue by Grawl** [2gis/tars#52]
I like to use indented Sass syntax (with `.sass` extension) but do not see that support in `tars-config.js`:

```js
/**
     * Css-preprocessor
     * Available 'scss', 'less' or 'stylus'
     * @type {String}
     */
    cssPreprocessor: 'scss',
```

If I trying to set `cssPreprocessor: 'sass'` I got this error:

```
➜  tars-test  gulp re-init
[18:08:49] Using gulpfile ~/Разработчик/tars-test/gulpfile.js
[18:08:49] Starting 're-init'...
[18:08:49] Starting 'service:remove-init-fs'...
[18:08:49] Finished 're-init' after 6.12 ms
[18:08:49] Finished 'service:remove-init-fs' after 47 ms
[18:08:49] Starting 'service:re-init'...
[18:08:49] Starting 'service:create-fs'...
[18:08:49] Finished 'service:create-fs' after 691 μs
[18:08:49] Starting 'service:init'...


🅃 🄰 🅁 🅂

Hi, I'm TARS. I will help you to make awesome markup!


You could find more info about me at https://github.com/artem-malko/tars/blob/master/README.md

Start your work with 'gulp dev'


[18:08:49] Finished 'service:re-init' after 3.58 ms
/Users/grawl/Разработчик/tars-test/tars/tasks/services/init.js:113
                    throw err;
                          ^
Error: https://github.com/artem-malko/tars-sass/archive/master.zip response code is 404 (Not Found)
  at /Users/grawl/Разработчик/tars-test/node_modules/download/node_modules/got/index.js:93:25
  at Unzip.<anonymous> (/Users/grawl/Разработчик/tars-test/node_modules/download/node_modules/got/node_modules/read-all-stream/index.js:41:3)
  at Unzip.g (events.js:199:16)
  at Unzip.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

**Comment by artem-malko** [comment]
Yeap, sass extension is not supported. Will implement it in 1.3.0.

**Comment by artem-malko** [comment]
#54 dublicate
