### ISSUE TITLE
Error: Cannot find module 'duplexer'

### ISSUE THREAD

**Issue by alexHlebnikov** [2gis/tars#86]
Вот такую ошибку получаю после gulp init: 
Error: Cannot find module 'duplexer'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\work\git\muscule\tars-master\node_modules\download\node_modules\stream-combiner\index.js:1:78)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Пробовал делать заново npm install и ставить gulp под sudo и без.
Разворачиваю текущий master.
Win 8.1x64

**Comment by alexHlebnikov** [comment]
Решил проблему *очисткой кеша* и переустановкой пакетов.
