### ISSUE TITLE
Не работает команда gulp init

### ISSUE THREAD

**Issue by rtxrulez** [2gis/tars#93]
rtx@rtx-job:~/projects/tars$ gulp init
[09:45:46] Warning: gulp version mismatch:
[09:45:46] Global gulp is 3.9.0
[09:45:46] Local gulp is 3.8.11
[09:46:10] Using gulpfile ~/projects/tars/gulpfile.js
[09:46:10] Starting 'init'...
[09:46:10] Starting 'service:create-fs'...
[09:46:10] Finished 'service:create-fs' after 698 μs
[09:46:10] Starting 'service:init'...

T A R S

Hi, I'm TARS. I will help you to make awesome markup!

You could find more info about me at https://github.com/artem-malko/tars/blob/master/README.md

Start your work with 'gulp dev'

[09:46:13] Finished 'init' after 2.17 s

/home/rtx/projects/tars/node_modules/download/node_modules/each-async/node_modules/onetime/index.js:15
                                throw new Error(fnName + ' can only be called once.');
                                      ^
Error: callback() can only be called once.
    at Request.<anonymous> (/home/rtx/projects/tars/node_modules/download/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/home/rtx/projects/tars/node_modules/download/node_modules/request/request.js:1006:12)
    at IncomingMessage.EventEmitter.emit (events.js:95:17)
    at readableAddChunk (_stream_readable.js:147:14)
    at IncomingMessage.Readable.push (_stream_readable.js:127:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:142:22)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:511:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
rtx@rtx-job:~/projects/tars$

**Comment by artem-malko** [comment]
@rtxrulez речь о kubunta, верно?

**Comment by rtxrulez** [comment]
Да.

**Comment by artem-malko** [comment]
@rtxrulez попробуй изменить версию пакета download до 3.3.0 в package.json и выполни npm i.

**Comment by artem-malko** [comment]
@rtxrulez или самую последнюю 4.1.4

**Comment by rtxrulez** [comment]
Поставил версию 4.1.4

rtx@rtx-job:~/projects/tars$ gulp init
[11:32:25] Warning: gulp version mismatch:
[11:32:25] Global gulp is 3.9.0
[11:32:25] Local gulp is 3.8.11
[11:32:38] Using gulpfile ~/projects/tars/gulpfile.js
[11:32:38] Starting 'init'...
[11:32:38] Starting 'service:create-fs'...
[11:32:38] Finished 'service:create-fs' after 848 μs
[11:32:38] Starting 'service:init'...


T A R S

Hi, I'm TARS. I will help you to make awesome markup!


You could find more info about me at https://github.com/artem-malko/tars/blob/master/README.md

Start your work with 'gulp dev'


[11:32:38] Finished 'init' after 3.32 ms

/home/rtx/projects/tars/tars/tasks/services/init.js:70
                    throw err;
                          ^
Error: EACCES, open '/home/rtx/projects/tars/.tmpTemplater/tars-handlebars-master/.gitignore'

**Comment by artem-malko** [comment]
@rtxrulez хм, кажется у тебя с правами что-то не так. Попробуй с sudo заинититься, это только для эксперимента. Потом так делать не надо.

**Comment by rtxrulez** [comment]
@artem-malko Вроде с root правами все прошло. Версия download 4.1.4
rtx@rtx-job:~/projects/tars$ sudo gulp init
[sudo] password for rtx: 
[12:59:26] Warning: gulp version mismatch:
[12:59:26] Global gulp is 3.9.0
[12:59:26] Local gulp is 3.8.11
[13:00:06] Using gulpfile ~/projects/tars/gulpfile.js
[13:00:06] Starting 'init'...
[13:00:06] Starting 'service:create-fs'...
[13:00:06] Finished 'service:create-fs' after 512 μs
[13:00:06] Starting 'service:init'...


T A R S

Hi, I'm TARS. I will help you to make awesome markup!


You could find more info about me at https://github.com/artem-malko/tars/blob/master/README.md

Start your work with 'gulp dev'


[13:00:06] Finished 'init' after 2.7 ms

---------------------------------------------------
TARS have been inited successfully!

You choose:
scss  as css-preprocessor
handlebars  as templater

---------------------------------------------------

rtx@rtx-job:~/projects/tars$

**Comment by artem-malko** [comment]
@rtxrulez Тогда что-то было не так у тебя настроено. Проверь, что у папки с проектом те же права, что и у пользователя. С рутом лучше не запускать сборщик.
Ишью закрою тогда?

**Comment by rtxrulez** [comment]
@artem-malko да. Спасибо.
